[package]
name = "pitchvis_viewer"
version = "0.1.0"
authors = ["Felix Monninger <felix.monninger@gmail.com>"]
edition = "2021"

[package.metadata.wasm-pack.profile.release]
wasm-opt = ['-Oz']
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# Enable a small amount of optimization in debug mode
[profile.dev]
opt-level = 1

# Enable high optimizations for dependencies (incl. Bevy), but not for our code:
[profile.dev.package."bevy"]
opt-level = 3

[target.'cfg(target_arch = "wasm32")'.profile.release]
strip = true
lto = "thin"
opt-level = 'z'

[lib]
name = "pitchvis_viewer_lib"
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "pitchvis"
path = "src/main.rs"

[dependencies]
anyhow = "1.0"
rustfft = "6.1.0"
apodize = "1.0.0"
num-complex = "0.4.2"
sprs = "0.11.0"
find_peaks = "0.1.5"
rubato = "0.12.0"
itertools = "0.10.5"
dagc = {version = "0.1.0", path = "../dagc" }
log = "0.4.17"
bevy = "0.10"
nalgebra = "0.32.2"
pitchvis_analysis = { path = "../pitchvis_analysis" }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
cpal = { version = "0.15.0", features = [] }
#, path = "../../cpal"  }
env_logger = "0.10.0"

[target.wasm32-unknown-unknown.dependencies]
cpal = { version = "0.15.0", features = ["wasm-bindgen"]}
#, path = "../../cpal" }
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
web-sys = { version = "0.3.35", features = [ "AudioContext", 
"AudioContextOptions", "AudioBuffer", "AudioBufferSourceNode", "AudioNode",  "AudioDestinationNode", 
"Window", "AudioContextState", "MediaStreamConstraints", "Navigator", "MediaDevices", "MediaStream", 
"MediaStreamAudioSourceNode", "AudioWorklet", "AudioWorkletNode", "AudioWorkletNodeOptions", "BaseAudioContext",
"MessagePort", "console", "MessageEvent", "MediaStreamTrack", "MediaTrackSettings"] }
js-sys = "0.3.61"
regex = "1"
